Nyaruko166/NovaStore_BE

src/main/java/com/sd64/novastore/model/Account.java
src/main/java/com/sd64/novastore/model/Address.java
src/main/java/com/sd64/novastore/model/Bill.java
src/main/java/com/sd64/novastore/model/BillDetail.java
src/main/java/com/sd64/novastore/model/BillHistory.java
src/main/java/com/sd64/novastore/model/Brand.java
src/main/java/com/sd64/novastore/model/Cart.java
src/main/java/com/sd64/novastore/model/CartDetail.java
src/main/java/com/sd64/novastore/model/Category.java
src/main/java/com/sd64/novastore/model/Color.java
src/main/java/com/sd64/novastore/model/ColorDetail.java
src/main/java/com/sd64/novastore/model/Image.java
src/main/java/com/sd64/novastore/model/Material.java
src/main/java/com/sd64/novastore/model/PaymentMethod.java
src/main/java/com/sd64/novastore/model/Product.java
src/main/java/com/sd64/novastore/model/ProductDetail.java
src/main/java/com/sd64/novastore/model/Promotion.java
src/main/java/com/sd64/novastore/model/PromotionDetail.java
src/main/java/com/sd64/novastore/model/Role.java
src/main/java/com/sd64/novastore/model/Size.java
src/main/java/com/sd64/novastore/model/SizeDetail.java
src/main/java/com/sd64/novastore/model/Staff.java
src/main/java/com/sd64/novastore/model/Voucher.java
src/main/java/com/sd64/novastore/model/VoucherDetail.java
src/main/java/com/sd64/novastore/repository/AccountRepository.java
src/main/java/com/sd64/novastore/repository/AddressRepository.java
src/main/java/com/sd64/novastore/repository/BillRepository.java
src/main/java/com/sd64/novastore/service/AccountService.java
src/main/java/com/sd64/novastore/service/impl/AccountServiceImpl.java

mapper entity

---

src/main/java/com/sd64/novastore/dto/ColorDetailRequest.java
src/main/java/com/sd64/novastore/dto/ColorRequest.java
src/main/java/com/sd64/novastore/dto/FormRequest.java
src/main/java/com/sd64/novastore/dto/ImageRequest.java
src/main/java/com/sd64/novastore/dto/MaterialRequest.java
src/main/java/com/sd64/novastore/dto/PaymentMethodRequest.java
src/main/java/com/sd64/novastore/dto/ProductDetailRequest.java
src/main/java/com/sd64/novastore/dto/ProductRequest.java
src/main/java/com/sd64/novastore/repository/ColorRepository.java
src/main/java/com/sd64/novastore/repository/FormRepository.java
src/main/java/com/sd64/novastore/repository/ImageRepository.java
src/main/java/com/sd64/novastore/repository/MaterialRepository.java
src/main/java/com/sd64/novastore/repository/PaymentMethodRepository.java
src/main/java/com/sd64/novastore/repository/ProductDetailRepository.java
src/main/java/com/sd64/novastore/repository/ProductRepository.java
src/main/java/com/sd64/novastore/service/impl/ColorDetailServiceImpl.java
src/main/java/com/sd64/novastore/service/impl/ColorServiceImpl.java
src/main/java/com/sd64/novastore/service/impl/FormServiceImpl.java
src/main/java/com/sd64/novastore/service/impl/ImageServiceImpl.java
src/main/java/com/sd64/novastore/service/impl/MaterialServiceImpl.java
src/main/java/com/sd64/novastore/service/impl/PaymentMethodServiceImpl.java
src/main/java/com/sd64/novastore/service/impl/ProductDetailServiceImpl.java
src/main/java/com/sd64/novastore/service/impl/ProductServiceImpl.java

Update API and Database

---

src/main/java/com/sd64/novastore/controller/admin/AccountController.java
src/main/java/com/sd64/novastore/controller/admin/AddressController.java
src/main/java/com/sd64/novastore/controller/admin/BillController.java
src/main/java/com/sd64/novastore/controller/admin/BillDetailController.java
src/main/java/com/sd64/novastore/controller/admin/BillHistoryController.java
src/main/java/com/sd64/novastore/controller/admin/BrandController.java
src/main/java/com/sd64/novastore/controller/admin/CartController.java
src/main/java/com/sd64/novastore/controller/admin/CartDetailController.java
src/main/java/com/sd64/novastore/controller/admin/CategoryController.java
src/main/java/com/sd64/novastore/controller/admin/ColorController.java
src/main/java/com/sd64/novastore/controller/admin/ColorDetailController.java
src/main/java/com/sd64/novastore/controller/admin/FormController.java
src/main/java/com/sd64/novastore/controller/admin/ImageController.java
src/main/java/com/sd64/novastore/controller/admin/MaterialController.java
src/main/java/com/sd64/novastore/controller/admin/PaymentController.java
src/main/java/com/sd64/novastore/controller/admin/PaymentMethodController.java
src/main/java/com/sd64/novastore/controller/admin/ProductController.java
src/main/java/com/sd64/novastore/controller/admin/ProductDetailController.java
src/main/java/com/sd64/novastore/controller/admin/PromotionController.java
src/main/java/com/sd64/novastore/controller/admin/PromotionDetailController.java
src/main/java/com/sd64/novastore/controller/admin/RoleController.java
src/main/java/com/sd64/novastore/controller/admin/SizeController.java
src/main/java/com/sd64/novastore/controller/admin/SizeDetailController.java
src/main/java/com/sd64/novastore/controller/admin/StaffController.java
src/main/java/com/sd64/novastore/controller/admin/VoucherController.java
src/main/java/com/sd64/novastore/controller/admin/VoucherDetailController.java
src/main/java/com/sd64/novastore/controller/admin/testController.java
src/main/resources/templates/admin/crud.html

HungUpdate

---

src/main/java/com/sd64/novastore/repository/BrandRepository.java
src/main/java/com/sd64/novastore/repository/CategoryRepository.java
src/main/java/com/sd64/novastore/repository/ColorRepository.java
src/main/java/com/sd64/novastore/repository/FormRepository.java
src/main/java/com/sd64/novastore/repository/MaterialRepository.java
src/main/java/com/sd64/novastore/repository/PromotionRepository.java
src/main/java/com/sd64/novastore/repository/SizeRepository.java
src/main/java/com/sd64/novastore/service/impl/BrandServiceImpl.java
src/main/java/com/sd64/novastore/service/impl/CategoryServiceImpl.java
src/main/java/com/sd64/novastore/service/impl/ColorServiceImpl.java
src/main/java/com/sd64/novastore/service/impl/FormServiceImpl.java
src/main/java/com/sd64/novastore/service/impl/MaterialServiceImpl.java
src/main/java/com/sd64/novastore/service/impl/PromotionServiceImpl.java
src/main/java/com/sd64/novastore/service/impl/SizeServiceImpl.java
src/main/resources/Nova_Store_DB.sql

replace smalldatetime to datetime

replace smalldatetime to datetime

---

src/main/java/com/sd64/novastore/controller/admin/BrandController.java
src/main/resources/static/admin/assets/css/style.css
src/main/resources/templates/admin/brand/brand.html
src/main/resources/templates/admin/fragments-admin.html

push again

---

src/main/java/com/sd64/novastore/controller/admin/PaymentMethodController.java
src/main/java/com/sd64/novastore/controller/admin/VoucherController.java
src/main/java/com/sd64/novastore/model/Voucher.java
src/main/java/com/sd64/novastore/repository/PaymentMethodRepository.java
src/main/java/com/sd64/novastore/repository/VoucherRepository.java
src/main/java/com/sd64/novastore/request/VoucherRequest.java
src/main/java/com/sd64/novastore/service/PaymentMethodService.java
src/main/java/com/sd64/novastore/service/VoucherService.java
src/main/java/com/sd64/novastore/service/impl/PaymentMethodServiceImpl.java
src/main/java/com/sd64/novastore/service/impl/VoucherServiceImpl.java
src/main/resources/templates/admin/payment-method/payment-method-detail.html
src/main/resources/templates/admin/payment-method/payment-method.html
src/main/resources/templates/admin/voucher/voucher-detail.html
src/main/resources/templates/admin/voucher/voucher.html

CRUD Voucher, PaymentMethod

---

src/main/java/com/sd64/novastore/controller/admin/CartController.java
src/main/java/com/sd64/novastore/controller/admin/CartDetailController.java
src/main/java/com/sd64/novastore/controller/admin/ProductDetailController.java
src/main/java/com/sd64/novastore/controller/admin/PromotionDetailController.java
src/main/java/com/sd64/novastore/repository/CartDetailRepository.java
src/main/java/com/sd64/novastore/repository/CartRepository.java
src/main/java/com/sd64/novastore/repository/ProductDetailRepository.java
src/main/java/com/sd64/novastore/repository/PromotionDetailRepository.java
src/main/java/com/sd64/novastore/service/CartDetailService.java
src/main/java/com/sd64/novastore/service/CartService.java
src/main/java/com/sd64/novastore/service/ProductDetailService.java
src/main/java/com/sd64/novastore/service/PromotionDetailService.java
src/main/java/com/sd64/novastore/service/impl/CartDetailServiceImpl.java
src/main/java/com/sd64/novastore/service/impl/CartServiceImpl.java
src/main/java/com/sd64/novastore/service/impl/ProductDetailServiceImpl.java
src/main/java/com/sd64/novastore/service/impl/PromotionDetailServiceImpl.java
src/main/resources/templates/admin/cart/cart-detail.html
src/main/resources/templates/admin/cart/cart.html
src/main/resources/templates/admin/cartdetail/cartdetail-detail.html
src/main/resources/templates/admin/cartdetail/cartdetail.html
src/main/resources/templates/admin/productdetail/productdetail-detail.html
src/main/resources/templates/admin/productdetail/productdetail.html
src/main/resources/templates/admin/promotiondetail/promotiondetail-detail.html
src/main/resources/templates/admin/promotiondetail/promotiondetail.html

HungCRUD Cart,CartDetail,Productdetail, Promotiondetail

HungCRUD Cart,CartDetail,Productdetail, Promotiondetail

---

src/main/java/com/sd64/novastore/controller/admin/BillHistoryController.java
src/main/java/com/sd64/novastore/repository/BillHistoryRepository.java
src/main/java/com/sd64/novastore/service/BillHistoryService.java
src/main/java/com/sd64/novastore/service/impl/BillHistoryServiceImpl.java
src/main/resources/templates/admin/bill-history/bill-history-detail.html
src/main/resources/templates/admin/bill-history/bill-history.html
src/main/resources/templates/admin/payment-method/payment-method-detail.html
src/main/resources/templates/admin/voucher/voucher-detail.html
src/main/resources/templates/admin/voucher/voucher.html

basic CRUD BillHistory

---

src/main/resources/Nova_Store_DB.sql

Update PromotionDetail, Voucher db

Update PromotionDetail, Voucher db

---

src/main/java/com/sd64/novastore/controller/user/UserBillController.java
src/main/java/com/sd64/novastore/controller/user/UserCartController.java
src/main/java/com/sd64/novastore/model/Bill.java
src/main/java/com/sd64/novastore/model/BillDetail.java
src/main/java/com/sd64/novastore/model/Customer.java
src/main/java/com/sd64/novastore/repository/AddressRepository.java
src/main/java/com/sd64/novastore/repository/BillRepository.java
src/main/java/com/sd64/novastore/service/AddressService.java
src/main/java/com/sd64/novastore/service/BillService.java
src/main/java/com/sd64/novastore/service/CartService.java
src/main/java/com/sd64/novastore/service/impl/AddressServiceImpl.java
src/main/java/com/sd64/novastore/service/impl/BillServiceImpl.java
src/main/java/com/sd64/novastore/service/impl/CartServiceImpl.java
src/main/resources/templates/user/cart.html
src/main/resources/templates/user/checkout.html
src/main/resources/templates/user/fragments.html
src/main/resources/templates/user/order-detail.html
src/main/resources/templates/user/order.html

Update basic online shopping

---

src/main/resources/Nova_Store_DB.sql

update cart database

---

src/main/java/com/sd64/novastore/controller/admin/BillController.java
src/main/java/com/sd64/novastore/controller/user/UserBillController.java
src/main/java/com/sd64/novastore/model/Bill.java
src/main/java/com/sd64/novastore/service/BillService.java
src/main/java/com/sd64/novastore/service/impl/BillServiceImpl.java
src/main/resources/templates/admin/bill/bill-detail.html
src/main/resources/templates/admin/bill/bill.html
src/main/resources/templates/user/cart.html
src/main/resources/templates/user/checkout.html
src/main/resources/templates/user/order-detail.html
src/main/resources/templates/user/order.html

Tuan update bill

---

src/main/resources/templates/user/detail.html

fix product quantity input

---

src/main/resources/Nova_Store_DB.sql

update address database

---

src/main/java/com/sd64/novastore/controller/user/HomeController.java
src/main/java/com/sd64/novastore/controller/user/UserBillController.java
src/main/java/com/sd64/novastore/controller/user/UserCartController.java
src/main/java/com/sd64/novastore/controller/user/rest/VoucherRestController.java
src/main/java/com/sd64/novastore/model/Bill.java
src/main/java/com/sd64/novastore/repository/BillRepository.java
src/main/java/com/sd64/novastore/repository/VoucherRepository.java
src/main/java/com/sd64/novastore/service/BillService.java
src/main/java/com/sd64/novastore/service/CartService.java
src/main/java/com/sd64/novastore/service/PaymentService.java
src/main/java/com/sd64/novastore/service/VoucherService.java
src/main/java/com/sd64/novastore/service/impl/BillServiceImpl.java
src/main/java/com/sd64/novastore/service/impl/CartServiceImpl.java
src/main/java/com/sd64/novastore/service/impl/PaymentServiceImpl.java
src/main/java/com/sd64/novastore/service/impl/VoucherServiceImpl.java
src/main/resources/templates/user/cart.html
src/main/resources/templates/user/checkout.html

update online shopping

---

src/main/java/com/sd64/novastore/controller/user/UserBillController.java
src/main/java/com/sd64/novastore/controller/user/UserCartController.java
src/main/java/com/sd64/novastore/controller/user/rest/AddressRestController.java
src/main/java/com/sd64/novastore/repository/PromotionDetailRepository.java
src/main/java/com/sd64/novastore/service/CartService.java
src/main/java/com/sd64/novastore/service/impl/CartServiceImpl.java
src/main/resources/templates/user/cart.html
src/main/resources/templates/user/checkout.html

update onl shopping

---

src/main/resources/application.properties

app properties

---

src/main/java/com/sd64/novastore/controller/user/HomeController.java
src/main/java/com/sd64/novastore/repository/user/ProductViewRepository.java
src/main/java/com/sd64/novastore/service/impl/user/ProductViewServiceImpl.java
src/main/java/com/sd64/novastore/service/user/ProductViewService.java
src/main/resources/templates/admin/product-detail/product-detail-update.html
src/main/resources/templates/admin/product/product-update.html
src/main/resources/templates/user/fragments.html
src/main/resources/templates/user/home.html
src/main/resources/templates/user/shop.html

update home and product shop

---

src/main/java/com/sd64/novastore/controller/user/HomeController.java
src/main/java/com/sd64/novastore/dto/common/ProductAndValueDiscountDto.java
src/main/java/com/sd64/novastore/dto/common/impl/ProductAndValueDiscountDtoImpl.java
src/main/java/com/sd64/novastore/repository/user/ProductViewRepository.java
src/main/java/com/sd64/novastore/service/impl/user/ProductViewServiceImpl.java
src/main/java/com/sd64/novastore/service/user/ProductViewService.java
src/main/resources/templates/user/detail.html

update product detail

---

src/main/java/com/sd64/novastore/service/impl/ProductServiceImpl.java

update price product discount

---

src/main/resources/templates/user/shop.html

update css slider price

---

src/main/java/com/sd64/novastore/controller/admin/AccountController.java
src/main/java/com/sd64/novastore/controller/admin/ColorController.java
src/main/java/com/sd64/novastore/controller/admin/SizeController.java
src/main/java/com/sd64/novastore/service/impl/BrandServiceImpl.java
src/main/java/com/sd64/novastore/service/impl/CategoryServiceImpl.java
src/main/java/com/sd64/novastore/service/impl/ColorServiceImpl.java
src/main/java/com/sd64/novastore/service/impl/FormServiceImpl.java
src/main/java/com/sd64/novastore/service/impl/MaterialServiceImpl.java
src/main/java/com/sd64/novastore/service/impl/SizeServiceImpl.java

update crud attribute product

---

src/main/java/com/sd64/novastore/controller/admin/ProductDetailController.java
src/main/java/com/sd64/novastore/repository/user/ProductViewRepository.java
src/main/resources/templates/admin/product-detail/product-detail-update.html

update image product

---

src/main/resources/Nova_Store_DB.sql

update insert product on DB

---

src/main/java/com/sd64/novastore/controller/admin/PromotionDetailController.java
src/main/java/com/sd64/novastore/repository/PromotionDetailRepository.java
src/main/java/com/sd64/novastore/repository/productPromotion.java
src/main/java/com/sd64/novastore/service/PromotionDetailService.java
src/main/java/com/sd64/novastore/service/impl/PromotionDetailServiceImpl.java
src/main/resources/templates/admin/product/product.html
src/main/resources/templates/admin/promotiondetail/promotiondetail.html

update promotion and promotion detail

---

src/main/java/com/sd64/novastore/controller/admin/ProductDetailController.java
src/main/java/com/sd64/novastore/dto/admin/Impl/ProductDetailDtoImpl.java
src/main/java/com/sd64/novastore/dto/admin/ProductDetailDto.java
src/main/java/com/sd64/novastore/repository/ProductDetailRepository.java
src/main/java/com/sd64/novastore/repository/user/ProductViewRepository.java
src/main/java/com/sd64/novastore/response/ProductDetailSearchResponse.java
src/main/java/com/sd64/novastore/service/ProductDetailService.java
src/main/java/com/sd64/novastore/service/impl/ProductDetailServiceImpl.java
src/main/java/com/sd64/novastore/service/impl/user/ProductViewServiceImpl.java
src/main/resources/templates/admin/account/account.html
src/main/resources/templates/admin/product-detail/product-detail.html
src/main/resources/templates/user/shop.html

update product detail price discount
